[package]
name = "3d_fps"
version = "0.1.0"
authors = ["Adam <adam@overflo.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.14.0"